language: python
python:
  - "3.6"
services:
  - mongodb
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
# command to run tests
script: ./runtests.sh
after_success:
  - coveralls
