language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install coverage
  - pip install git+https://github.com/wonderpush/python3-gcm.git
  - python setup.py develop
# command to run tests
script: ./runtests.sh