language: python
python:
  - "3.4"
services:
  - mongodb
# command to install dependencies
install:
  - pip install -U setuptools pip
  - python setup.py develop
  - pip install coveralls
# command to run tests
script: ./runtests.sh
after_success:
  - coveralls
